// crates/bindings-typescript/src/react/SpacetimeDBProvider.ts
import {
  DbConnectionBuilder,
  type DbConnectionBase,
} from '../sdk/db_connection_impl';
import * as React from 'react';
import { SpacetimeDBContext } from './useSpacetimeDB';
import type { ConnectionState } from './connection_state';
import { ConnectionId } from '../lib/connection_id';
import {
  ConnectionManager,
  type ConnectionState as ManagerConnectionState,
} from '../sdk/connection_manager';

export interface SpacetimeDBProviderProps<
  DbConnection extends DbConnectionBase<any>,
> {
  connectionBuilder: DbConnectionBuilder<DbConnection>;
  children?: React.ReactNode;
}

export function SpacetimeDBProvider<
  DbConnection extends DbConnectionBase<any>,
>({
  connectionBuilder,
  children,
}: SpacetimeDBProviderProps<DbConnection>): React.JSX.Element {
  const uri = connectionBuilder.getUri();
  const moduleName = connectionBuilder.getModuleName();
  const key = React.useMemo(
    () => ConnectionManager.getKey(uri, moduleName),
    [uri, moduleName]
  );

  const fallbackStateRef = React.useRef<ManagerConnectionState>({
    isActive: false,
    identity: undefined,
    token: undefined,
    connectionId: ConnectionId.random(),
    connectionError: undefined,
  });

  const subscribe = React.useCallback(
    (onStoreChange: () => void) =>
      ConnectionManager.subscribe(key, onStoreChange),
    [key]
  );
  const getSnapshot = React.useCallback(
    () => ConnectionManager.getSnapshot(key) ?? fallbackStateRef.current,
    [key]
  );
  const getServerSnapshot = React.useCallback(
    () => fallbackStateRef.current,
    []
  );

  const state = React.useSyncExternalStore(
    subscribe,
    getSnapshot,
    getServerSnapshot
  );

  const getConnection = React.useCallback(
    () => ConnectionManager.getConnection<DbConnection>(key),
    [key]
  );

  const contextValue = React.useMemo<ConnectionState>(
    () => ({ ...state, getConnection }),
    [state, getConnection]
  );

  React.useEffect(() => {
    ConnectionManager.retain(key, connectionBuilder);
    return () => {
      ConnectionManager.release(key);
    };
  }, [key, connectionBuilder]);

  return React.createElement(
    SpacetimeDBContext.Provider,
    { value: contextValue },
    children
  );
}

// crates/bindings-typescript/src/solid/SpacetimeDBProvider.ts
import {
  DbConnectionBuilder,
  type DbConnectionBase,
} from '../sdk/db_connection_impl';
import { onCleanup, createMemo, createComputed } from 'solid-js';
import { createStore } from 'solid-js/store';
import { SpacetimeDBContext } from './useSpacetimeDB';
import type { ConnectionState } from './connection_state';
import { ConnectionId } from '../lib/connection_id';
import {
  ConnectionManager,
  type ConnectionState as ManagerConnectionState,
} from '../sdk/connection_manager';

export interface SpacetimeDBProviderProps<
  DbConnection extends DbConnectionBase<any>,
> {
  connectionBuilder: DbConnectionBuilder<DbConnection>;
  children?: any;
}

export function SpacetimeDBProvider<DbConnection extends DbConnectionBase<any>>(
  props: SpacetimeDBProviderProps<DbConnection>
) {
  const uri = () => props.connectionBuilder.getUri();
  const moduleName = () => props.connectionBuilder.getModuleName();

  const key = createMemo(() => ConnectionManager.getKey(uri(), moduleName()));

  const fallbackState: ManagerConnectionState = {
    isActive: false,
    identity: undefined,
    token: undefined,
    connectionId: ConnectionId.random(),
    connectionError: undefined,
  };

  const [state, setState] = createStore<ManagerConnectionState>(fallbackState);

  // Subscribe to ConnectionManager state changes
  createComputed(() => {
    const currentKey = key();

    const unsubscribe = ConnectionManager.subscribe(currentKey, () => {
      const snapshot =
        ConnectionManager.getSnapshot(currentKey) ?? fallbackState;
      setState(snapshot);
    });

    // Load initial snapshot
    const snapshot = ConnectionManager.getSnapshot(currentKey) ?? fallbackState;
    setState(snapshot);

    onCleanup(() => {
      unsubscribe();
    });
  });

  const getConnection = () =>
    ConnectionManager.getConnection<DbConnection>(key());

  const contextValue: ConnectionState = {
    get isActive() {
      return state.isActive;
    },
    get identity() {
      return state.identity;
    },
    get token() {
      return state.token;
    },
    get connectionId() {
      return state.connectionId;
    },
    get connectionError() {
      return state.connectionError;
    },
    getConnection,
  };

  // Retain / release lifecycle
  createComputed(() => {
    const currentKey = key();
    ConnectionManager.retain(currentKey, props.connectionBuilder);

    onCleanup(() => {
      ConnectionManager.release(currentKey);
    });
  });

  return SpacetimeDBContext.Provider({
    value: contextValue,
    get children() {
      return props.children;
    },
  });
}
