// crates/bindings-typescript/src/react/useReducer.ts
import { useCallback, useEffect, useRef } from 'react';
import type { UntypedReducerDef } from '../sdk/reducers.ts';
import { useSpacetimeDB } from './useSpacetimeDB.ts';
import type { ParamsType } from '../sdk/index.ts';

export function useReducer<ReducerDef extends UntypedReducerDef>(
  reducerDef: ReducerDef
): (...params: ParamsType<ReducerDef>) => Promise<void> {
  const { getConnection, isActive } = useSpacetimeDB();
  const reducerName = reducerDef.accessorName;

  // Holds calls made before the connection exists
  const queueRef = useRef<
    {
      params: ParamsType<ReducerDef>;
      resolve: () => void;
      reject: (err: unknown) => void;
    }[]
  >([]);

  // Flush when we finally have a connection
  useEffect(() => {
    const conn = getConnection();
    if (!conn) {
      return;
    }
    const fn = (conn.reducers as any)[reducerName] as (
      ...p: ParamsType<ReducerDef>
    ) => Promise<void>;
    if (queueRef.current.length) {
      const pending = queueRef.current.splice(0);
      for (const item of pending) {
        fn(...item.params).then(item.resolve, item.reject);
      }
    }
  }, [getConnection, reducerName, isActive]);

  return useCallback(
    (...params: ParamsType<ReducerDef>) => {
      const conn = getConnection();
      if (!conn) {
        return new Promise<void>((resolve, reject) => {
          queueRef.current.push({ params, resolve, reject });
        });
      }
      const fn = (conn.reducers as any)[reducerName] as (
        ...p: ParamsType<ReducerDef>
      ) => Promise<void>;
      return fn(...params);
    },
    [getConnection, reducerName]
  );
}

// crates/bindings-typescript/src/solid/useReducer.ts
import { createEffect } from 'solid-js';
import type { UntypedReducerDef } from '../sdk/reducers.ts';
import { useSpacetimeDB } from './useSpacetimeDB.ts';
import type { ParamsType } from '../sdk/index.ts';

export function useReducer<ReducerDef extends UntypedReducerDef>(
  reducerDef: ReducerDef
): (...params: ParamsType<ReducerDef>) => Promise<void> {
  const { getConnection, isActive } = useSpacetimeDB();
  const reducerName = reducerDef.accessorName;

  // Holds calls made before the connection exists
  const queue: {
    params: ParamsType<ReducerDef>;
    resolve: () => void;
    reject: (err: unknown) => void;
  }[] = [];

  // Flush when we finally have a connection
  createEffect(() => {
    if (!isActive) return;

    const conn = getConnection();
    if (!conn) return;

    const fn = (conn.reducers as any)[reducerName] as (
      ...p: ParamsType<ReducerDef>
    ) => Promise<void>;

    if (queue.length) {
      const pending = queue.splice(0);
      for (const item of pending) {
        fn(...item.params).then(item.resolve, item.reject);
      }
    }
  });

  return (...params: ParamsType<ReducerDef>) => {
    const conn = getConnection();
    if (!conn) {
      return new Promise<void>((resolve, reject) => {
        queue.push({ params, resolve, reject });
      });
    }
    const fn = (conn.reducers as any)[reducerName] as (
      ...p: ParamsType<ReducerDef>
    ) => Promise<void>;
    return fn(...params);
  };
}
